name: Demo

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Start Kindlefy Demo
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Kindlefy
        uses: ./
        with:
          kindle_email: 'demo@kindle.com'
          sender: '[]'
          sources: '[{ "type": "manga", "name": "One Piece" }, { "type": "rss", "url": "https://dev.to/feed" }]'
