name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Kindlefy
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Test Kindlefy
        uses: ./
        with:
          kindle_email: 'test@kindle.com'
          sender: '[]'
          sources: '[]'